var MeshIntersector_module = (() => {
  var _scriptName = typeof document != 'undefined' ? document.currentScript?.src : undefined;
  if (typeof __filename != 'undefined') _scriptName = _scriptName || __filename;
  return (
async function(moduleArg = {}) {
  var moduleRtn;

var h=moduleArg,aa,p,ba=new Promise((a,b)=>{aa=a;p=b}),ca="object"==typeof window,da="undefined"!=typeof WorkerGlobalScope,ea="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node&&"renderer"!=process.type,fa=Object.assign({},h),q=(a,b)=>{throw b;},t="",ha,ia;
if(ea){var fs=require("fs");require("path");t=__dirname+"/";ia=a=>{a=ja(a)?new URL(a):a;return fs.readFileSync(a)};ha=async a=>{a=ja(a)?new URL(a):a;return fs.readFileSync(a,void 0)};process.argv.slice(2);q=(a,b)=>{process.exitCode=a;throw b;}}else if(ca||da)da?t=self.location.href:"undefined"!=typeof document&&document.currentScript&&(t=document.currentScript.src),_scriptName&&(t=_scriptName),t.startsWith("blob:")?t="":t=t.substr(0,t.replace(/[?#].*/,"").lastIndexOf("/")+1),da&&(ia=a=>{var b=new XMLHttpRequest;
b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ha=async a=>{if(ja(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);};var ka=h.print||console.log.bind(console),v=h.printErr||console.error.bind(console);
Object.assign(h,fa);fa=null;var la=h.wasmBinary,ma,na=!1,oa,pa,y,z,qa,A,B,ra,sa,ta,ua,va=a=>a.startsWith("data:application/octet-stream;base64,"),ja=a=>a.startsWith("file://");
function wa(){var a=ma.buffer;h.HEAP8=pa=new Int8Array(a);h.HEAP16=z=new Int16Array(a);h.HEAPU8=y=new Uint8Array(a);h.HEAPU16=qa=new Uint16Array(a);h.HEAP32=A=new Int32Array(a);h.HEAPU32=B=new Uint32Array(a);h.HEAPF32=ra=new Float32Array(a);h.HEAPF64=ua=new Float64Array(a);h.HEAP64=sa=new BigInt64Array(a);h.HEAPU64=ta=new BigUint64Array(a)}var xa=[],ya=[],za=[];function Aa(){var a=h.preRun.shift();xa.unshift(a)}var C=0,D=null;
function Ba(a){h.onAbort?.(a);a="Aborted("+a+")";v(a);na=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");p(a);throw a;}var Ca;async function Da(a){if(!la)try{var b=await ha(a);return new Uint8Array(b)}catch{}if(a==Ca&&la)a=new Uint8Array(la);else if(ia)a=ia(a);else throw"both async and sync fetching of the wasm failed";return a}
async function Ea(a,b){try{var c=await Da(a);return await WebAssembly.instantiate(c,b)}catch(d){v(`failed to asynchronously prepare wasm: ${d}`),Ba(d)}}async function Fa(a){var b=Ca;if(!(la||"function"!=typeof WebAssembly.instantiateStreaming||va(b)||ja(b)||ea))try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){v(`wasm streaming compile failed: ${d}`),v("falling back to ArrayBuffer instantiation")}return Ea(b,a)}
class Ga{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Ia=a=>{for(;0<a.length;)a.shift()(h)},Ja=h.noExitRuntime||!0,Ka=a=>{if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a},La,E=a=>{for(var b="";y[a];)b+=La[y[a++]];return b},F={},I={},Ma={},J,Na=a=>{throw new J(a);},N,P=(a,b,c)=>{function d(g){g=c(g);if(g.length!==a.length)throw new N("Mismatched type converter count");for(var m=0;m<a.length;++m)O(a[m],g[m])}a.forEach(g=>Ma[g]=b);var e=Array(b.length),f=[],l=0;b.forEach((g,m)=>{I.hasOwnProperty(g)?
e[m]=I[g]:(f.push(g),F.hasOwnProperty(g)||(F[g]=[]),F[g].push(()=>{e[m]=I[g];++l;l===f.length&&d(e)}))});0===f.length&&d(e)};function Oa(a,b,c={}){var d=b.name;if(!a)throw new J(`type "${d}" must have a positive integer typeid pointer`);if(I.hasOwnProperty(a)){if(c.pa)return;throw new J(`Cannot register type '${d}' twice`);}I[a]=b;delete Ma[a];F.hasOwnProperty(a)&&(b=F[a],delete F[a],b.forEach(e=>e()))}function O(a,b,c={}){return Oa(a,b,c)}
var Pa=(a,b,c)=>{switch(b){case 1:return c?d=>pa[d]:d=>y[d];case 2:return c?d=>z[d>>1]:d=>qa[d>>1];case 4:return c?d=>A[d>>2]:d=>B[d>>2];case 8:return c?d=>sa[d>>3]:d=>ta[d>>3];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Qa=a=>{throw new J(a.N.R.O.name+" instance already deleted");},Ra=!1,Sa=()=>{},Ta=(a,b,c)=>{if(b===c)return a;if(void 0===c.T)return null;a=Ta(a,b,c.T);return null===a?null:c.ma(a)},Ua={},Va={},Wa=(a,b)=>{if(void 0===b)throw new J("ptr should not be undefined");
for(;a.T;)b=a.da(b),a=a.T;return Va[b]},Xa=(a,b)=>{if(!b.R||!b.P)throw new N("makeClassHandle requires ptr and ptrType");if(!!b.U!==!!b.S)throw new N("Both smartPtrType and smartPtr must be specified");b.count={value:1};return Q(Object.create(a,{N:{value:b,writable:!0}}))},Q=a=>{if("undefined"===typeof FinalizationRegistry)return Q=b=>b,a;Ra=new FinalizationRegistry(b=>{b=b.N;--b.count.value;0===b.count.value&&(b.S?b.U.Y(b.S):b.R.O.Y(b.P))});Q=b=>{var c=b.N;c.S&&Ra.register(b,{N:c},b);return b};Sa=
b=>{Ra.unregister(b)};return Q(a)},Ya=[];function Za(){}
var R=(a,b)=>Object.defineProperty(b,"name",{value:a}),$a=(a,b)=>{if(void 0===h[a].W){var c=h[a];h[a]=function(...d){if(!h[a].W.hasOwnProperty(d.length))throw new J(`Function '${b}' called with an invalid number of arguments (${d.length}) - expects one of (${h[a].W})!`);return h[a].W[d.length].apply(this,d)};h[a].W=[];h[a].W[c.ia]=c}},ab=(a,b,c)=>{if(h.hasOwnProperty(a)){if(void 0===c||void 0!==h[a].W&&void 0!==h[a].W[c])throw new J(`Cannot register public name '${a}' twice`);$a(a,a);if(h[a].W.hasOwnProperty(c))throw new J(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);
h[a].W[c]=b}else h[a]=b,h[a].ia=c},bb=a=>{a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?`_${a}`:a};function cb(a,b,c,d,e,f,l,g){this.name=a;this.constructor=b;this.$=c;this.Y=d;this.T=e;this.na=f;this.da=l;this.ma=g}var db=(a,b,c)=>{for(;b!==c;){if(!b.da)throw new J(`Expected null or instance of ${c.name}, got an instance of ${b.name}`);a=b.da(a);b=b.T}return a};
function eb(a,b){if(null===b){if(this.ga)throw new J(`null is not a valid ${this.name}`);return 0}if(!b.N)throw new J(`Cannot pass "${Ka(b)}" as a ${this.name}`);if(!b.N.P)throw new J(`Cannot pass deleted object as a pointer of type ${this.name}`);return db(b.N.P,b.N.R.O,this.O)}
function fb(a,b){if(null===b){if(this.ga)throw new J(`null is not a valid ${this.name}`);if(this.fa){var c=this.sa();null!==a&&a.push(this.Y,c);return c}return 0}if(!b||!b.N)throw new J(`Cannot pass "${Ka(b)}" as a ${this.name}`);if(!b.N.P)throw new J(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.ea&&b.N.R.ea)throw new J(`Cannot convert argument of type ${b.N.U?b.N.U.name:b.N.R.name} to parameter type ${this.name}`);c=db(b.N.P,b.N.R.O,this.O);if(this.fa){if(void 0===b.N.S)throw new J("Passing raw pointer to smart pointer is illegal");
switch(this.ua){case 0:if(b.N.U===this)c=b.N.S;else throw new J(`Cannot convert argument of type ${b.N.U?b.N.U.name:b.N.R.name} to parameter type ${this.name}`);break;case 1:c=b.N.S;break;case 2:if(b.N.U===this)c=b.N.S;else{var d=b.clone();c=this.ta(c,S(()=>d["delete"]()));null!==a&&a.push(this.Y,c)}break;default:throw new J("Unsupporting sharing policy");}}return c}
function gb(a,b){if(null===b){if(this.ga)throw new J(`null is not a valid ${this.name}`);return 0}if(!b.N)throw new J(`Cannot pass "${Ka(b)}" as a ${this.name}`);if(!b.N.P)throw new J(`Cannot pass deleted object as a pointer of type ${this.name}`);if(b.N.R.ea)throw new J(`Cannot convert argument of type ${b.N.R.name} to parameter type ${this.name}`);return db(b.N.P,b.N.R.O,this.O)}function hb(a){return this.fromWireType(B[a>>2])}
function ib(a,b,c,d,e,f,l,g,m,k,n){this.name=a;this.O=b;this.ga=c;this.ea=d;this.fa=e;this.ra=f;this.ua=l;this.ka=g;this.sa=m;this.ta=k;this.Y=n;e||void 0!==b.T?this.toWireType=fb:(this.toWireType=d?eb:gb,this.V=null)}
var jb=(a,b,c)=>{if(!h.hasOwnProperty(a))throw new N("Replacing nonexistent public symbol");void 0!==h[a].W&&void 0!==c?h[a].W[c]=b:(h[a]=b,h[a].ia=c)},kb=[],lb,T=(a,b)=>{a=E(a);var c=kb[b];c||(b>=kb.length&&(kb.length=b+1),kb[b]=c=lb.get(b));if("function"!=typeof c)throw new J(`unknown function pointer with signature ${a}: ${b}`);return c},mb,ob=a=>{a=nb(a);var b=E(a);U(a);return b},V=(a,b)=>{function c(f){e[f]||I[f]||(Ma[f]?Ma[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new mb(`${a}: `+
d.map(ob).join([", "]));},pb=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(B[b+4*d>>2]);return c},qb=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};function rb(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].V)return!0;return!1}
function sb(a){var b=Function;if(!(b instanceof Function))throw new TypeError(`new_ called with constructor type ${typeof b} which is not a function`);var c=R(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function ub(a,b,c,d,e){var f=b.length;if(2>f)throw new J("argTypes array size mismatch! Must at least get return value and 'this' types!");var l=null!==b[1]&&!1,g=rb(b),m="void"!==b[0].name;c=[a,Na,c,d,qb,b[0],b[1]];for(d=0;d<f-2;++d)c.push(b[d+2]);if(!g)for(d=l?1:2;d<b.length;++d)null!==b[d].V&&c.push(b[d].V);g=rb(b);d=b.length-2;var k=[],n=["fn"];l&&n.push("thisWired");for(f=0;f<d;++f)k.push(`arg${f}`),n.push(`arg${f}Wired`);k=k.join(",");n=n.join(",");k=`return function (${k}) {\n`;g&&(k+="var destructors = [];\n");
var r=g?"destructors":"null",u="humanName throwBindingError invoker fn runDestructors retType classParam".split(" ");l&&(k+=`var thisWired = classParam['toWireType'](${r}, this);\n`);for(f=0;f<d;++f)k+=`var arg${f}Wired = argType${f}['toWireType'](${r}, arg${f});\n`,u.push(`argType${f}`);k+=(m||e?"var rv = ":"")+`invoker(${n});\n`;if(g)k+="runDestructors(destructors);\n";else for(f=l?1:2;f<b.length;++f)e=1===f?"thisWired":"arg"+(f-2)+"Wired",null!==b[f].V&&(k+=`${e}_dtor(${e});\n`,u.push(`${e}_dtor`));
m&&(k+="var ret = retType['fromWireType'](rv);\nreturn ret;\n");let [G,w]=[u,k+"}\n"];G.push(w);b=sb(G)(...c);return R(a,b)}
for(var vb=(a,b,c)=>{if(!(a instanceof Object))throw new J(`${c} with invalid "this": ${a}`);if(!(a instanceof b.O.constructor))throw new J(`${c} incompatible with "this" of type ${a.constructor.name}`);if(!a.N.P)throw new J(`cannot call emscripten binding method ${c} on deleted object`);return db(a.N.P,a.N.R.O,b.O)},wb=[],W=[],xb=a=>{9<a&&0===--W[a+1]&&(W[a]=void 0,wb.push(a))},X=a=>{if(!a)throw new J("Cannot use deleted val. handle = "+a);return W[a]},S=a=>{switch(a){case void 0:return 2;case null:return 4;
case !0:return 6;case !1:return 8;default:const b=wb.pop()||W.length;W[b]=a;W[b+1]=1;return b}},yb={name:"emscripten::val",fromWireType:a=>{var b=X(a);xb(a);return b},toWireType:(a,b)=>S(b),X:8,readValueFromPointer:hb,V:null},zb=(a,b)=>{switch(b){case 4:return function(c){return this.fromWireType(ra[c>>2])};case 8:return function(c){return this.fromWireType(ua[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},Ab=a=>{a=a.trim();const b=a.indexOf("(");return-1!==b?a.substr(0,
b):a},Bb="undefined"!=typeof TextDecoder?new TextDecoder:void 0,Cb=(a,b=0,c=NaN)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Bb)return Bb.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var l=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|l:(e&7)<<18|f<<12|l<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},
Db="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0,Eb=(a,b)=>{var c=a>>1;for(var d=c+b/2;!(c>=d)&&qa[c];)++c;c<<=1;if(32<c-a&&Db)return Db.decode(y.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=z[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c},Fb=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)z[b>>1]=a.charCodeAt(e),b+=2;z[b>>1]=0;return b-d},Gb=a=>2*a.length,Hb=(a,b)=>{for(var c=0,d="";!(c>=b/4);){var e=A[a+
4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d},Ib=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var l=a.charCodeAt(++e);f=65536+((f&1023)<<10)|l&1023}A[b>>2]=f;b+=4;if(b+4>c)break}A[b>>2]=0;return b-d},Jb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b},Kb=0,Lb=(a,b)=>{var c=I[a];if(void 0===
c)throw a=`${b} has unknown type ${ob(a)}`,new J(a);return c},Mb=(a,b,c)=>{var d=[];a=a.toWireType(d,c);d.length&&(B[b>>2]=S(d));return a},Nb=[],Ob={},Pb=a=>{var b=Ob[a];return void 0===b?E(a):b},Qb=()=>"object"==typeof globalThis?globalThis:Function("return this")(),Rb=a=>{var b=Nb.length;Nb.push(a);return b},Sb=(a,b)=>{for(var c=Array(a),d=0;d<a;++d)c[d]=Lb(B[b+4*d>>2],"parameter "+d);return c},Y={},Tb=a=>{oa=a;Ja||0<Kb||(h.onExit?.(a),na=!0);q(a,new Ga(a))},Ub=a=>{if(!na)try{if(a(),!(Ja||0<Kb))try{oa=
a=oa,Tb(a)}catch(b){b instanceof Ga||"unwind"==b||q(1,b)}}catch(b){b instanceof Ga||"unwind"==b||q(1,b)}},Vb=[null,[],[]],Wb=Array(256),Xb=0;256>Xb;++Xb)Wb[Xb]=String.fromCharCode(Xb);La=Wb;J=h.BindingError=class extends Error{constructor(a){super(a);this.name="BindingError"}};N=h.InternalError=class extends Error{constructor(a){super(a);this.name="InternalError"}};
Object.assign(Za.prototype,{isAliasOf:function(a){if(!(this instanceof Za&&a instanceof Za))return!1;var b=this.N.R.O,c=this.N.P;a.N=a.N;var d=a.N.R.O;for(a=a.N.P;b.T;)c=b.da(c),b=b.T;for(;d.T;)a=d.da(a),d=d.T;return b===d&&c===a},clone:function(){this.N.P||Qa(this);if(this.N.ba)return this.N.count.value+=1,this;var a=Q,b=Object,c=b.create,d=Object.getPrototypeOf(this),e=this.N;a=a(c.call(b,d,{N:{value:{count:e.count,aa:e.aa,ba:e.ba,P:e.P,R:e.R,S:e.S,U:e.U}}}));a.N.count.value+=1;a.N.aa=!1;return a},
["delete"](){this.N.P||Qa(this);if(this.N.aa&&!this.N.ba)throw new J("Object already scheduled for deletion");Sa(this);var a=this.N;--a.count.value;0===a.count.value&&(a.S?a.U.Y(a.S):a.R.O.Y(a.P));this.N.ba||(this.N.S=void 0,this.N.P=void 0)},isDeleted:function(){return!this.N.P},deleteLater:function(){this.N.P||Qa(this);if(this.N.aa&&!this.N.ba)throw new J("Object already scheduled for deletion");Ya.push(this);this.N.aa=!0;return this}});
Object.assign(ib.prototype,{oa(a){this.ka&&(a=this.ka(a));return a},ja(a){this.Y?.(a)},X:8,readValueFromPointer:hb,fromWireType:function(a){function b(){return this.fa?Xa(this.O.$,{R:this.ra,P:c,U:this,S:a}):Xa(this.O.$,{R:this,P:a})}var c=this.oa(a);if(!c)return this.ja(a),null;var d=Wa(this.O,c);if(void 0!==d){if(0===d.N.count.value)return d.N.P=c,d.N.S=a,d.clone();d=d.clone();this.ja(a);return d}d=this.O.na(c);d=Ua[d];if(!d)return b.call(this);d=this.ea?d.la:d.pointerType;var e=Ta(c,this.O,d.O);
return null===e?b.call(this):this.fa?Xa(d.O.$,{R:d,P:e,U:this,S:a}):Xa(d.O.$,{R:d,P:e})}});mb=h.UnboundTypeError=((a,b)=>{var c=R(b,function(d){this.name=b;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(a.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:`${this.name}: ${this.message}`};return c})(Error,"UnboundTypeError");
W.push(0,1,void 0,1,null,1,!0,1,!1,1);h.count_emval_handles=()=>W.length/2-5-wb.length;
var $b={A:()=>Ba(""),t:(a,b,c)=>{b=E(b);O(a,{name:b,fromWireType:d=>d,toWireType:function(d,e){if("bigint"!=typeof e&&"number"!=typeof e)throw new TypeError(`Cannot convert "${Ka(e)}" to ${this.name}`);"number"==typeof e&&(e=BigInt(e));return e},X:8,readValueFromPointer:Pa(b,c,-1==b.indexOf("u")),V:null})},E:(a,b,c,d)=>{b=E(b);O(a,{name:b,fromWireType:function(e){return!!e},toWireType:function(e,f){return f?c:d},X:8,readValueFromPointer:function(e){return this.fromWireType(y[e])},V:null})},C:(a,b,
c,d,e,f,l,g,m,k,n,r,u)=>{n=E(n);f=T(e,f);g&&=T(l,g);k&&=T(m,k);u=T(r,u);var G=bb(n);ab(G,function(){V(`Cannot construct ${n} due to unbound types`,[d])});P([a,b,c],d?[d]:[],w=>{w=w[0];if(d){var K=w.O;var L=K.$}else L=Za.prototype;w=R(n,function(...Ha){if(Object.getPrototypeOf(this)!==M)throw new J("Use 'new' to construct "+n);if(void 0===x.Z)throw new J(n+" has no accessible constructor");var tb=x.Z[Ha.length];if(void 0===tb)throw new J(`Tried to invoke ctor of ${n} with invalid number of parameters (${Ha.length}) - expected (${Object.keys(x.Z).toString()}) parameters instead!`);
return tb.apply(this,Ha)});var M=Object.create(L,{constructor:{value:w}});w.prototype=M;var x=new cb(n,w,M,u,K,f,g,k);if(x.T){var H;(H=x.T).ha??(H.ha=[]);x.T.ha.push(x)}K=new ib(n,x,!0,!1,!1);H=new ib(n+"*",x,!1,!1,!1);L=new ib(n+" const*",x,!1,!0,!1);Ua[a]={pointerType:H,la:L};jb(G,w);return[K,H,L]})},w:(a,b,c,d,e,f)=>{var l=pb(b,c);e=T(d,e);P([],[a],g=>{g=g[0];var m=`constructor ${g.name}`;void 0===g.O.Z&&(g.O.Z=[]);if(void 0!==g.O.Z[b-1])throw new J(`Cannot register multiple constructors with identical number of parameters (${b-
1}) for class '${g.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);g.O.Z[b-1]=()=>{V(`Cannot construct ${g.name} due to unbound types`,l)};P([],l,k=>{k.splice(1,0,null);g.O.Z[b-1]=ub(m,k,e,f);return[]});return[]})},n:(a,b,c,d,e,f,l,g,m,k)=>{b=E(b);e=T(d,e);P([],[a],n=>{n=n[0];var r=`${n.name}.${b}`,u={get(){V(`Cannot access ${r} due to unbound types`,[c,l])},enumerable:!0,configurable:!0};u.set=m?()=>V(`Cannot access ${r} due to unbound types`,
[c,l]):()=>{throw new J(r+" is a read-only property");};Object.defineProperty(n.O.$,b,u);P([],m?[c,l]:[c],G=>{var w=G[0],K={get(){var M=vb(this,n,r+" getter");return w.fromWireType(e(f,M))},enumerable:!0};if(m){m=T(g,m);var L=G[1];K.set=function(M){var x=vb(this,n,r+" setter"),H=[];m(k,x,L.toWireType(H,M));qb(H)}}Object.defineProperty(n.O.$,b,K);return[]});return[]})},B:a=>O(a,yb),s:(a,b,c)=>{b=E(b);O(a,{name:b,fromWireType:d=>d,toWireType:(d,e)=>e,X:8,readValueFromPointer:zb(b,c),V:null})},d:(a,
b,c,d,e,f,l)=>{var g=pb(b,c);a=E(a);a=Ab(a);e=T(d,e);ab(a,function(){V(`Cannot call ${a} due to unbound types`,g)},b-1);P([],g,m=>{m=[m[0],null].concat(m.slice(1));jb(a,ub(a,m,e,f,l),b-1);return[]})},i:(a,b,c,d,e)=>{b=E(b);-1===e&&(e=4294967295);e=g=>g;if(0===d){var f=32-8*c;e=g=>g<<f>>>f}var l=b.includes("unsigned")?function(g,m){return m>>>0}:function(g,m){return m};O(a,{name:b,fromWireType:e,toWireType:l,X:8,readValueFromPointer:Pa(b,c,0!==d),V:null})},b:(a,b,c)=>{function d(f){return new e(pa.buffer,
B[f+4>>2],B[f>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][b];c=E(c);O(a,{name:c,fromWireType:d,X:8,readValueFromPointer:d},{pa:!0})},D:(a,b)=>{b=E(b);O(a,{name:b,fromWireType:function(c){for(var d=B[c>>2],e=c+4,f,l=e,g=0;g<=d;++g){var m=e+g;if(g==d||0==y[m])l=l?Cb(y,l,m-l):"",void 0===f?f=l:(f+=String.fromCharCode(0),f+=l),l=m+1}U(c);return f},toWireType:function(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));
var e,f="string"==typeof d;if(!(f||d instanceof Uint8Array||d instanceof Uint8ClampedArray||d instanceof Int8Array))throw new J("Cannot pass non-string to std::string");var l;if(f)for(e=l=0;e<d.length;++e){var g=d.charCodeAt(e);127>=g?l++:2047>=g?l+=2:55296<=g&&57343>=g?(l+=4,++e):l+=3}else l=d.length;e=l;l=Yb(4+e+1);g=l+4;B[l>>2]=e;if(f){if(f=g,g=e+1,e=y,0<g){g=f+g-1;for(var m=0;m<d.length;++m){var k=d.charCodeAt(m);if(55296<=k&&57343>=k){var n=d.charCodeAt(++m);k=65536+((k&1023)<<10)|n&1023}if(127>=
k){if(f>=g)break;e[f++]=k}else{if(2047>=k){if(f+1>=g)break;e[f++]=192|k>>6}else{if(65535>=k){if(f+2>=g)break;e[f++]=224|k>>12}else{if(f+3>=g)break;e[f++]=240|k>>18;e[f++]=128|k>>12&63}e[f++]=128|k>>6&63}e[f++]=128|k&63}}e[f]=0}}else if(f)for(f=0;f<e;++f){m=d.charCodeAt(f);if(255<m)throw U(l),new J("String has UTF-16 code units that do not fit in 8 bits");y[g+f]=m}else for(f=0;f<e;++f)y[g+f]=d[f];null!==c&&c.push(U,l);return l},X:8,readValueFromPointer:hb,V(c){U(c)}})},q:(a,b,c)=>{c=E(c);if(2===b){var d=
Eb;var e=Fb;var f=Gb;var l=g=>qa[g>>1]}else 4===b&&(d=Hb,e=Ib,f=Jb,l=g=>B[g>>2]);O(a,{name:c,fromWireType:g=>{for(var m=B[g>>2],k,n=g+4,r=0;r<=m;++r){var u=g+4+r*b;if(r==m||0==l(u))n=d(n,u-n),void 0===k?k=n:(k+=String.fromCharCode(0),k+=n),n=u+b}U(g);return k},toWireType:(g,m)=>{if("string"!=typeof m)throw new J(`Cannot pass non-string to C++ string type ${c}`);var k=f(m),n=Yb(4+k+b);B[n>>2]=k/b;e(m,n+4,k+b);null!==g&&g.push(U,n);return n},X:8,readValueFromPointer:hb,V(g){U(g)}})},F:(a,b)=>{b=E(b);
O(a,{qa:!0,name:b,X:0,fromWireType:()=>{},toWireType:()=>{}})},v:()=>{Ja=!1;Kb=0},o:(a,b,c)=>{a=X(a);b=Lb(b,"emval::as");return Mb(b,c,a)},j:(a,b,c,d)=>{a=Nb[a];b=X(b);return a(null,b,c,d)},m:(a,b,c,d,e)=>{a=Nb[a];b=X(b);c=Pb(c);return a(b,b[c],d,e)},a:xb,r:a=>{if(0===a)return S(Qb());a=Pb(a);return S(Qb()[a])},g:(a,b,c)=>{b=Sb(a,b);var d=b.shift();a--;var e="return function (obj, func, destructorsRef, args) {\n",f=0,l=[];0===c&&l.push("obj");for(var g=["retType"],m=[d],k=0;k<a;++k)l.push("arg"+k),
g.push("argType"+k),m.push(b[k]),e+=`  var arg${k} = argType${k}.readValueFromPointer(args${f?"+"+f:""});\n`,f+=b[k].X;e+=`  var rv = ${1===c?"new func":"func.call"}(${l.join(", ")});\n`;d.qa||(g.push("emval_returnValue"),m.push(Mb),e+="  return emval_returnValue(retType, destructorsRef, rv);\n");g.push(e+"};\n");a=sb(g)(...m);c=`methodCaller<(${b.map(n=>n.name).join(", ")}) => ${d.name}>`;return Rb(R(c,a))},k:a=>{a=Pb(a);return S(h[a])},f:(a,b)=>{a=X(a);b=X(b);return S(a[b])},h:a=>{9<a&&(W[a+1]+=
1)},c:a=>S(Pb(a)),e:a=>{var b=X(a);qb(b);xb(a)},l:(a,b,c)=>{a=X(a);b=X(b);c=X(c);a[b]=c},p:(a,b)=>{a=Lb(a,"_emval_take_value");a=a.readValueFromPointer(b);return S(a)},x:(a,b)=>{Y[a]&&(clearTimeout(Y[a].id),delete Y[a]);if(!b)return 0;var c=setTimeout(()=>{delete Y[a];Ub(()=>Zb(a,performance.now()))},b);Y[a]={id:c,va:b};return 0},y:a=>{var b=y.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,
d)/65536))-ma.buffer.byteLength+65535)/65536|0;try{ma.grow(d);wa();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},z:(a,b,c,d)=>{for(var e=0,f=0;f<c;f++){var l=B[b>>2],g=B[b+4>>2];b+=8;for(var m=0;m<g;m++){var k=y[l+m],n=Vb[a];0===k||10===k?((1===a?ka:v)(Cb(n)),n.length=0):n.push(k)}e+=g}B[d>>2]=e;return 0},u:Tb},Z;
(async function(){function a(d){Z=d.exports;ma=Z.G;wa();lb=Z.M;ya.unshift(Z.H);C--;h.monitorRunDependencies?.(C);0==C&&D&&(d=D,D=null,d());return Z}C++;h.monitorRunDependencies?.(C);var b={a:$b};if(h.instantiateWasm)try{return h.instantiateWasm(b,a)}catch(d){v(`Module.instantiateWasm callback failed with error: ${d}`),p(d)}Ca??=va("MeshIntersector_module.wasm")?"MeshIntersector_module.wasm":h.locateFile?h.locateFile("MeshIntersector_module.wasm",t):t+"MeshIntersector_module.wasm";try{var c=await Fa(b);
return a(c.instance)}catch(d){return p(d),Promise.reject(d)}})();var Yb=a=>(Yb=Z.I)(a),U=a=>(U=Z.J)(a),nb=a=>(nb=Z.K)(a),Zb=(a,b)=>(Zb=Z.L)(a,b);
function ac(){function a(){h.calledRun=!0;if(!na){Ia(ya);aa(h);h.onRuntimeInitialized?.();if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var b=h.postRun.shift();za.unshift(b)}Ia(za)}}if(0<C)D=ac;else{if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Aa();Ia(xa);0<C?D=ac:h.setStatus?(h.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>h.setStatus(""),1);a()},1)):a()}}
if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();ac();moduleRtn=ba;


  return moduleRtn;
}
);
})();
if (typeof exports === 'object' && typeof module === 'object') {
  module.exports = MeshIntersector_module;
  // This default export looks redundant, but it allows TS to import this
  // commonjs style module.
  module.exports.default = MeshIntersector_module;
} else if (typeof define === 'function' && define['amd'])
  define([], () => MeshIntersector_module);
